export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL'
export const OPEN_REGISTER_MODAL = 'OPEN_REGISTER_MODAL'
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL'
export const ADD_TODO = 'ADD_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'
export const CLOSE_ADD_TODO_MODAL = 'CLOSE_ADD_TODO_MODAL'
export const IS_LOGINED = 'IS_LOGINED'
export const EXIT_LOGIN = 'EXIT_LOGIN'

